version: '3.8'

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    entrypoint: ["anvil", "--host", "0.0.0.0", "--fork-url", "https://rpc.ankr.com/eth"]
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./site:/usr/share/nginx/html
